### ISSUE TITLE
Drop dpkg-vendor config?

### ISSUE THREAD

**Issue by zeha** [grml/grml-keyring#7]
I don't think we win anything by having it, and if we expect users to install this package, they shouldn't have the file?

https://github.com/grml/grml-debian-keyring/blob/master/origins/Grml

**Comment by zeha** [comment]
@evgeni @mika @jkirk appreciate your input here

**Comment by guillemj** [comment]
The origin file gives information about the vendor that generated this package, and it makes sense to be provided by a package shipping the archive keyring (which would be the boostrap package to install to get other packages from that origin). In this case it is tied through the `Origin` field in the `debian/control` file, which can help users know where this originated from, or I think for stuff like `reportbug` to know where to report issues at (in theory it should either use the `Bugs` field from package in the dpkg status file coming from the .deb or I'd assume if that is missing, then try to get the vendor information from the `Origin` field, then the vendor file and the `Bugs` field from there).

The origin file does not necessarily need to denote that the system this package got installed into is a Grml system, that would normally only be done via the `default` symlink.

Not sure if that clarifies things, or whether the file might still be deemed irrelevant? If it clarifies, then perhaps that indicates that we should improve documentation somewhere, I guess I could take a stab at writing something like the above in `dpkg-vendor(1)` or `deb-origin(5)`.

**Comment by zeha** [comment]
@guillemj thanks for taking the time and explaining this. Indeed it helps my understanding / clarifies the file usage.
Based on this I think we should keep the file. Indeed we set Origin: Grml in d/control for the packages.

**Comment by guillemj** [comment]
BTW (as I cannot recall now whether refs from commits get  notified), tried to improve the above mentioned manual pages with the commit referenced above. I'm happy to further try to clarify or extend that if people find it lacking/unclear!

**Comment by zeha** [comment]
> BTW (as I cannot recall now whether refs from commits get notified), tried to improve the above mentioned manual pages with the commit referenced above. I'm happy to further try to clarify or extend that if people find it lacking/unclear!

I didn't get a notification about the commit; the new text in the manual page makes it clear to me!

Many thanks!

**Comment by zeha** [comment]
With the input and clarifications from @guillemj I think I'll just close this issue, and we keep shipping https://github.com/grml/grml-debian-keyring/blob/master/origins/Grml

@guillemj  Last minute thought: these files have to be in /etc, they cannot be in /usr, correct?

**Comment by guillemj** [comment]
> Last minute thought: these files have to be in /etc, they cannot be in /usr, correct?

Yes, while this might be possible in the future, it is currently not, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041210.
